# Pandas Methods

## head(), tail()

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('c:\\Users\\KRISHNA\\Desktop\\Programming\\Data Science\\Test CSV files\\rows10.csv')    #head method
df.head()

,S.NO,Name,Frc,val,deval,anl,grscc,location,part,mean
0,1,"Eldon Base for stackable storage shelf, platinum",Muhammed MacIntyre,3,-213.25,38.94,35.00,Nunavut,Storage & Organization,0.80
1,2,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Barry French,293,457.81,208.16,68.02,Nunavut,Appliances,0.58
2,3,"Cardinal Slant-D速 Ring Binder, Heavy Gauge Vinyl",Barry French,293,46.71,8.69,2.99,Nunavut,Binders and Binder Accessories,0.39
3,4,R380,Clay Rozendal,483,1198.97,195.99,3.99,Nunavut,Telephones and Communication,0.58
4,5,Holmes HEPA Air Purifier,Carlos Soltero,515,30.94,21.78,5.94,Nunavut,Appliances,0.50

In [4]:
df = pd.read_csv('c:\\Users\\KRISHNA\\Desktop\\Programming\\Data Science\\Test CSV files\\rows10.csv')    #head method
df.head(3)

,S.NO,Name,Frc,val,deval,anl,grscc,location,part,mean
0,1,"Eldon Base for stackable storage shelf, platinum",Muhammed MacIntyre,3,-213.25,38.94,35.00,Nunavut,Storage & Organization,0.80
1,2,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Barry French,293,457.81,208.16,68.02,Nunavut,Appliances,0.58
2,3,"Cardinal Slant-D速 Ring Binder, Heavy Gauge Vinyl",Barry French,293,46.71,8.69,2.99,Nunavut,Binders and Binder Accessories,0.39

In [5]:
df = pd.read_csv('c:\\Users\\KRISHNA\\Desktop\\Programming\\Data Science\\Test CSV files\\rows10.csv')    #tail method
df.tail()

,S.NO,Name,Frc,val,deval,anl,grscc,location,part,mean
5,6,G.E. Longer-Life Indoor Recessed Floodlight Bulbs,Carlos Soltero,515,4.43,6.64,4.95,Nunavut,Office Furnishings,0.37
6,7,"Angle-D Binders with Locking Rings, Label Holders",Carl Jackson,613,-54.04,7.30,7.72,Nunavut,Binders and Binder Accessories,0.38
7,8,"SAFCO Mobile Desk Side File, Wire Frame",Carl Jackson,613,127.70,42.76,6.22,Nunavut,Storage & Organization,NaN
8,9,"SAFCO Commercial Wire Shelving, Black",Monica Federle,643,-695.26,138.14,35.00,Nunavut,Storage & Organization,NaN
9,10,Xerox 198,Dorothy Badders,678,-226.36,4.98,8.33,Nunavut,Paper,0.38

In [6]:
df = pd.read_csv('c:\\Users\\KRISHNA\\Desktop\\Programming\\Data Science\\Test CSV files\\rows10.csv')    #tail method
df.tail(2)

,S.NO,Name,Frc,val,deval,anl,grscc,location,part,mean
8,9,"SAFCO Commercial Wire Shelving, Black",Monica Federle,643,-695.26,138.14,35.00,Nunavut,Storage & Organization,NaN
9,10,Xerox 198,Dorothy Badders,678,-226.36,4.98,8.33,Nunavut,Paper,0.38

# dtype , true_values , false_values

In [31]:
df = pd.read_csv('c:\\Users\\KRISHNA\\Desktop\\Programming\\Data Science\\Test CSV files\\rows10.csv',dtype = {'val':'float64'})
df

,S.NO,Name,Frc,val,deval,anl,grscc,location,part,mean
0,1,"Eldon Base for stackable storage shelf, platinum",Muhammed MacIntyre,3.0,-213.25,38.94,35.00,Nunavut,Storage & Organization,0.80
1,2,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Barry French,293.0,457.81,208.16,68.02,Nunavut,Appliances,0.58
2,3,"Cardinal Slant-D速 Ring Binder, Heavy Gauge Vinyl",Barry French,293.0,46.71,8.69,2.99,Nunavut,Binders and Binder Accessories,0.39
3,4,R380,Clay Rozendal,483.0,1198.97,195.99,3.99,Nunavut,Telephones and Communication,0.58
4,5,Holmes HEPA Air Purifier,Carlos Soltero,515.0,30.94,21.78,5.94,Nunavut,Appliances,0.50
5,6,G.E. Longer-Life Indoor Recessed Floodlight Bulbs,Carlos Soltero,515.0,4.43,6.64,4.95,Nunavut,Office Furnishings,0.37
6,7,"Angle-D Binders with Locking Rings, Label Holders",Carl Jackson,613.0,-54.04,7.30,7.72,Nunavut,Binders and Binder Accessories,0.38
7,8,"SAFCO Mobile Desk Side File, Wire Frame",Carl Jackson,613.0,127.70,42.76,6.22,Nunavut,Storage & Organization,NaN
8,9,"SAFCO Commercial Wire Shelving, Black",Monica Federle,643.0,-695.26,138.14,35.00,Nunavut,Storage & Organization,NaN
9,10,Xerox 198,Dorothy Badders,678.0,-226.36,4.98,8.33,Nunavut,Paper,0.38

In [32]:
df = pd.read_csv('c:\\Users\\KRISHNA\\Desktop\\Programming\\Data Science\\Test CSV files\\rows10.csv',dtype = {'val':'str','S.NO':'float64','anl':'int32'})
df

ValueError: cannot safely convert passed user dtype of int32 for float64 dtyped data in column 5

In [37]:
df = pd.read_csv('c:\\Users\\KRISHNA\\Desktop\\Programming\\Data Science\\Test CSV files\\rows10.csv',true_values = ['yes'],false_values = ['no'])
df

,S.NO,Name,Frc,invert,val,deval,anl,grscc,location,part,mean
0,1,"Eldon Base for stackable storage shelf, platinum",Muhammed MacIntyre,True,3,-213.25,38.94,35.00,Nunavut,Storage & Organization,0.80
1,2,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Barry French,True,293,457.81,208.16,68.02,Nunavut,Appliances,0.58
2,3,"Cardinal Slant-D速 Ring Binder, Heavy Gauge Vinyl",Barry French,True,293,46.71,8.69,2.99,Nunavut,Binders and Binder Accessories,0.39
3,4,R380,Clay Rozendal,False,483,1198.97,195.99,3.99,Nunavut,Telephones and Communication,0.58
4,5,Holmes HEPA Air Purifier,Carlos Soltero,False,515,30.94,21.78,5.94,Nunavut,Appliances,0.50
5,6,G.E. Longer-Life Indoor Recessed Floodlight Bulbs,Carlos Soltero,True,515,4.43,6.64,4.95,Nunavut,Office Furnishings,0.37
6,7,"Angle-D Binders with Locking Rings, Label Holders",Carl Jackson,False,613,-54.04,7.30,7.72,Nunavut,Binders and Binder Accessories,0.38
7,8,"SAFCO Mobile Desk Side File, Wire Frame",Carl Jackson,False,613,127.70,42.76,6.22,Nunavut,Storage & Organization,NaN
8,9,"SAFCO Commercial Wire Shelving, Black",Monica Federle,True,643,-695.26,138.14,35.00,Nunavut,Storage & Organization,NaN
9,10,Xerox 198,Dorothy Badders,False,678,-226.36,4.98,8.33,Nunavut,Paper,0.38